title: CORTX FDMI Word Count Application 
description: A CORTX FDMI Application that counts the number of words in new objects data. 
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
